### ISSUE TITLE
2nd one , in windows wallet.

### ISSUE THREAD

**Issue by ghost** [PoWx-Org/obtc-bluewallet#4]
in windows wallet one done sync with blockchain
and all fine ok.
issue=then close wallet and restart wallet once
its lagging nearly halfen hour.
its taking too late ,
please solve this problem

**Comment by pkvk** [comment]
We suggest to try Electrum wallet instead: https://github.com/PoWx-Org/electrum-experimental/releases/tag/v0

If you are not satisfied, feel free to report the issue in the more appropriate place: https://github.com/PoWx-Org/obtc-core/issues

We will close this one. Thank you.
